server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: dealer-portal
  
  datasource:
    url: jdbc:postgresql://localhost:5432/dealer_portal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin123
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: dealer-portal-secret-key-2024
  expiration: 86400000 # 24 hours

# Swagger Configuration
springfox:
  documentation:
    swagger-ui:
      enabled: true
    auto-startup: true

# Logging
logging:
  level:
    com.dealer: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Profiles
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/dealer_portal_dev

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

---
spring:
  profiles: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
jwt:
  secret: ${JWT_SECRET} 